format: 
	yapf -ri .

biquad:
	python3 IIR-biquad-16kHz-44100.py


butterworth:
	python3 IIR-Butterworth-16kHz.py    > workfiles/butterworth_16kHz.h
	python3 IIR-Butterworth-12.5kHz.py  > workfiles/butterworth_12.5kHz.h


