format: 
	yapf -ri .

biquad:
	python3 IIR-biquad-16kHz-44100.py


butterworth:
	python3 IIR-Butterworth-16kHz.py > workfiles/butterworth_VFO.h
	python3 IIR-Butterworth-2756Hz.py > workfiles/butterworth_LFO.h


