name: build-for-release

on:
  workflow_dispatch:  
  
env:
  rack-sdk-version: latest
  rack-plugin-toolchain-dir: /home/build/rack-plugin-toolchain

defaults:
  run:
    shell: bash

jobs:

  build:
    name: ${{ matrix.platform }}
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/qno/rack-plugin-toolchain-win-linux
      options: --user root
    
    strategy:
      matrix:
        platform: [win-x64, lin-x64]

    steps:
      - uses: actions/checkout@v3

      - name: Build plugin
        run: |
             export PLUGIN_DIR=$GITHUB_WORKSPACE
             pushd ${{ env.rack-plugin-toolchain-dir }}
             make plugin-build-${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.rack-plugin-toolchain-dir }}/plugin-build
          name: sn-2.0.0-${{ matrix.platform }}

  build-mac:
    name: mac
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [x64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Get Rack-SDK
        run: |
          pushd $HOME
          wget -O Rack-SDK.zip "https://vcvrack.com/downloads/Rack-SDK-2.5.2-mac-x64+arm64.zip"
          unzip Rack-SDK.zip

      - name: Build plugin
        run: |
          CROSS_COMPILE_TARGET_x64=x86_64-apple-darwin
          CROSS_COMPILE_TARGET_arm64=arm64-apple-darwin
          export RACK_DIR=$HOME/Rack-SDK
          export CROSS_COMPILE=$CROSS_COMPILE_TARGET_${{ matrix.platform }}
          make dep
          make dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.vcvplugin
          name: sn-2.0.0-mac-${{ matrix.platform }}

  build-mac-11:
    name: mac
    runs-on: macos-11

    strategy:
      fail-fast: false
      matrix:
        platform: [x64]

    steps:
      - uses: actions/checkout@v3

      - name: Get Rack-SDK
        run: |
          pushd $HOME
          wget -O Rack-SDK.zip "https://vcvrack.com/downloads/Rack-SDK-2.5.2-mac-x64+arm64.zip"
          unzip Rack-SDK.zip

      - name: Build plugin
        run: |
          CROSS_COMPILE_TARGET_x64=x86_64-apple-darwin
          CROSS_COMPILE_TARGET_arm64=arm64-apple-darwin
          export RACK_DIR=$HOME/Rack-SDK
          export CROSS_COMPILE=$CROSS_COMPILE_TARGET_${{ matrix.platform }}
          make dep
          make dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.vcvplugin
          name: sn-2.0.0-mac-11-${{ matrix.platform }}

