name: linux

on:
  workflow_dispatch:  
  
env:
  rack-sdk-version: latest
  rack-plugin-toolchain-dir: /home/build/rack-plugin-toolchain

defaults:
  run:
    shell: bash

jobs:
  build:
    name: linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [x64]

    steps:
      - uses: actions/checkout@v3
      - name: Get Rack-SDK
        run: |
          pushd $HOME
          wget -O Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-${{ env.rack-sdk-version }}-lin-${{ matrix.platform }}.zip
          unzip Rack-SDK.zip

      - name: Build plugin
        run: |
          export RACK_DIR=$HOME/Rack-SDK
          make dep
          make dist

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: dist/*.vcvplugin
      #     name: linux-${{ matrix.platform }}
