name: windows

on:
  workflow_dispatch:  

env:
  rack-sdk-version: latest
  rack-plugin-toolchain-dir: /home/build/rack-plugin-toolchain

defaults:
  run:
    shell: bash

jobs:
  build-windows:
    name: windows
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [x64]

    steps:
      - uses: actions/checkout@v3
      - name: Get Rack-SDK
        run: |
          pushd $HOME
          C:\msys64\usr\bin\wget.exe -O Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-${{ env.rack-sdk-version }}-win-${{ matrix.platform }}.zip
          unzip Rack-SDK.zip

      # - name: Build plugin
      #   run: |
      #     export RACK_DIR=$HOME/Rack-SDK
      #     make dep
      #     make dist

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: dist/*.vcvplugin
      #     windows: linux-${{ matrix.platform }}
